server:
  port: 8080

spring:
  application:
    name: ping

management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true

#tracing:
#  url: http://localhost:4318/v1/traces

tracing:
  url: http://localhost:4317

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG